exit if subprocesses fail
As per #2

diff --git a/goesimage b/goesimage
--- a/goesimage
+++ b/goesimage
@@ -15,7 +15,22 @@ Options:
                 large (1808x1808),
                 xlarge (10848x10848)
     -o      output the filename of the image but do not set it as the background
+    -v      verbose output
     -h      display usage"
+}
+
+log() {
+    if [ "$verbose" = true ]; then
+        echo "$*"
+    fi
+}
+
+execute() {
+    log "Executing command: $*"
+    if ! "$@"; then
+        log "Failed to execute command: $*"
+        exit 4
+    fi;
 }
 
 get_size() {
@@ -41,7 +56,7 @@ get_images() {
         url="https://cdn.star.nesdis.noaa.gov/$i/ABI/FD/GEOCOLOR/$dimensions.jpg"
         filename="$i.jpg"
         filename_list+=("$filename")
-        curl --silent --output "$filename" "$url"
+        execute curl --silent --output "$filename" "$url"
     done
 }
 
@@ -61,7 +76,7 @@ check_images() {
 
 process_images() {
     if [ ${#satellite_list[@]} -gt 1 ]; then
-        convert -border 20 -bordercolor black +append "${filename_list[@]}" latest.jpg
+        execute convert -border 20 -bordercolor black +append "${filename_list[@]}" latest.jpg
     else
         mv "$filename" latest.jpg
     fi
@@ -81,12 +96,12 @@ set_bg() {
     if [ "$output_only" = true ]; then
         echo "$output_dir/latest.jpg"
     else
-        feh --bg-max "$output_dir/latest.jpg"
+        execute feh --bg-max "$output_dir/latest.jpg"
     fi
 }
 
 satellite_list=()
-while getopts "s:ewoh" opt; do
+while getopts "s:ewovh" opt; do
     case $opt in
         s)
             size_opt=$OPTARG
@@ -99,6 +114,9 @@ while getopts "s:ewoh" opt; do
             ;;
         o)
             output_only=true
+            ;;
+        v)
+            verbose=true
             ;;
         h)
             usage
